version: '3.8'

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    container_name: careminds-mongodb-replica
    ports:
      - "27019:27017"
    environment:
      - MONGO_REPLICA_PORT=27017
      - MONGO_REPLICA_HOST=mongodb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=careminds
    volumes:
      - mongodb_replica_data:/data/db
    networks:
      - careminds-network
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3020:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://admin:password123@mongodb:27017/careminds?authSource=admin&directConnection=true
    container_name: careminds-app
    depends_on:
      - mongodb
    networks:
      - careminds-network

networks:
  careminds-network:
    driver: bridge

volumes:
  mongodb_replica_data: 