version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: careminds-mongodb
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=careminds
    volumes:
      - mongodb_data:/data/db
    networks:
      - careminds-network
    command: mongod --auth

networks:
  careminds-network:
    driver: bridge

volumes:
  mongodb_data:
